image:
  repository: ghcr.io/panixida-templates/dotnet-backend-template/api
  tag: "160"

migrations:
  image:
    repository: ghcr.io/panixida-templates/dotnet-backend-template/ef-migrator
    tag: "160"
