image:
  repository: ghcr.io/panixida-templates/dotnet-backend-template/api
  tag: dev-183

migrations:
  image:
    repository: ghcr.io/panixida-templates/dotnet-backend-template/ef-migrator
    tag: dev-183
