{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotnet-template.serviceAccountName" . }}
  labels:
    {{- include "dotnet-template.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotnet-template.externalSecretsServiceAccountName" . }}
  labels:
    {{- include "dotnet-template.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.externalSecrets.serviceAccount.syncWave | quote }}
automountServiceAccountToken: {{ .Values.externalSecrets.serviceAccount.automountServiceAccountToken }}
{{- end }}
